#!/usr/bin/env bash
# Convenience wrapper around decrypt.py.
#
# Usage:
#   ./decrypt.sh path/to/secret.cdoc [output_dir]
#
# Uses certs/mallory.key (generated by gen-certs.sh) as the private key.
set -euo pipefail

cd "$(dirname "$0")"

IN="${1:?Usage: $0 <path/to/secret.cdoc> [output_dir]}"
OUT="${2:-decrypted}"
KEY="certs/mallory.key"

if [[ ! -f "$KEY" ]]; then
    echo "[!] $KEY not found. Run ./gen-certs.sh first." >&2
    exit 1
fi

# Make sure the cryptography package is installed.
python3 -c 'import cryptography' 2>/dev/null || {
    echo "[*] Installing Python 'cryptography' (one-time)..."
    pip3 install --quiet --user cryptography
}

python3 decrypt.py --in "$IN" --key "$KEY" --out "$OUT"
echo
echo "[+] Files recovered in: $OUT/"
ls -la "$OUT"/
